name: misq_p2p
description: Bisq P2P library for Dart
version: 0.0.1
author: Kieran Harkin <kieran@harkin.me>
homepage: https://github.com/v0l/misq

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  protobuf: ^1.0.0
  sqflite: ^1.1.7+1
  path: ^1.6.4
  logging: ^0.11.3+2
  socks:
    git:
      url: https://github.com/v0l/socks

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/data/btc_mainnet.seednodes
    - lib/data/btc_testnet.seednodes
    - lib/data/btc_regtest.seednodes